language: node_js

node_js:
  - "6.9.1"

sudo: required

notifications:
  email:
    recipients:
      - rojasagustin90@gmail.com
      - recheconea@gmail.com
    on_success: change
    on_failure: always

install:
  - npm install

script:
  - node app.js &
  - npm test